{deleteVehicle _x} forEach nearestObjects [PatientSpawn, ["B_Survivor_F"], 5];
sleep 1;
groupPatient=createGroup west;
'B_Survivor_F' createUnit [getPosATL patientSpawnPoint, groupPatient,'pat1=this; dostop pat1'];
pat1 setDir 194.3;
pat1 setPos getPos PatientSpawn;
pat1 setVariable ["lambs_danger_disableAI", true];
[pat1, selectRandom[0,0.5,0.7,1.0], "leg_r", selectrandom ["backblast", "bite", "bullet", "explosive", "falling", "grenade", "punch", "ropeburn", "shell", "stab", "unknown", "vehiclecrash"]] call ace_medical_fnc_addDamageToUnit;
[pat1, selectRandom[0,0.5,0.7,1.0], "leg_l", selectrandom ["backblast", "bite", "bullet", "explosive", "falling", "grenade", "punch", "ropeburn", "shell", "stab", "unknown", "vehiclecrash"]] call ace_medical_fnc_addDamageToUnit;
[pat1, selectRandom[0,0.5,0.7,0.9,1.2,1.5], "body", selectrandom ["backblast", "bite", "bullet", "explosive", "falling", "grenade", "punch", "ropeburn", "shell", "stab", "unknown", "vehiclecrash"]] call ace_medical_fnc_addDamageToUnit;
[pat1, selectRandom[0,0.5,0.7,1.0], "head", selectrandom ["backblast", "bite", "bullet", "explosive", "falling", "grenade", "punch", "ropeburn", "shell", "stab", "unknown", "vehiclecrash"]] call ace_medical_fnc_addDamageToUnit;
[pat1, selectRandom[0,0.5,0.7,1.0], "hand_r", selectrandom ["backblast", "bite", "bullet", "explosive", "falling", "grenade", "punch", "ropeburn", "shell", "stab", "unknown", "vehiclecrash"]] call ace_medical_fnc_addDamageToUnit;
[pat1, selectRandom[0,0.5,0.7,1.0], "hand_l", selectrandom ["backblast", "bite", "bullet", "explosive", "falling", "grenade", "punch", "ropeburn", "shell", "stab", "unknown", "vehiclecrash"]] call ace_medical_fnc_addDamageToUnit;
pat1 setVariable ["acex_headless_blacklist", true, true];
pat1 setVariable ["ace_medical_ai_lastFired", 9999999];
sleep 1;
(group pat1) setGroupIdGlobal ["Patient"];
groupPatient setBehaviour "CARELESS";
systemchat "Tactical Field Care Training (serious wounds) has started!";